### ISSUE TITLE
Add code formatter support

### ISSUE THREAD

**Issue by karma-sun** [marlon407/code-groovy#2]
Please Add code formatter support

**Comment by KurtYilmaz** [comment]
This is a pretty important issue I think. Are there plans to address this?

**Comment by docwhat** [comment]
The only groovy formatter in the world I’m aware of is embedded in the NetBeans editor. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by nvuillam** [comment]
Working on it :p 
https://www.npmjs.com/package/npm-groovy-lint

**Comment by karma-sun** [comment]
project seems abandoned,use vscode-groovy-lint instead

**Comment by nvuillam** [comment]
https://marketplace.visualstudio.com/items?itemName=NicolasVuillamy.vscode-groovy-lint :)
